version: '3.8'

services:
    backend:
        build: ./backend
        ports:
            - "8080:8080"
        environment:
            HOSTNAME: ${HOSTNAME}
            JWT_SECRET: ${JWT_SECRET}
            AUTH_CALLBACK_URL: ${AUTH_CALLBACK_URL}
            LOGIN_REDIRECT_URL: ${LOGIN_REDIRECT_URL}

            POSTGRES_URL: db:5432/postgres
            POSTGRES_USERNAME: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

            GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
            GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

    db:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
